### PR TITLE
Support Rails 8.0

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by bartostefan** [comment]
Somebody to merge it? Thanks :)

**Comment by n-rodriguez** [comment]
ping @blowmage

**Review by zenspider — COMMENTED** [review]
OK. I'mma step in and try to maintain this for a while... As such I'm still catching up... I've asked for some changes to #255 and going to tend to that before the 8.0 PRs... as such I suspect it'll cause conflict on your branch when it gets finalized and merged.

**Comment by zenspider** [comment]
Please rebase and fix conflicts OR tell me you're letting this go and I can try to take it over

**Comment by n-rodriguez** [comment]
@zenspider done!

**Comment by zenspider** [comment]
I went with #258 as it covered changing all the URLs in the rdoc. If you rebase and fix conflicts I can see about merging any differences you still have.

**Comment by n-rodriguez** [comment]
@zenspider I'm fine with https://github.com/minitest/minitest-rails/pull/258. Thank you!

**Pull request closed without merging**
